### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XUEYULIANG** [daniellerch/pySTC#2]
I got error report as below, could you please give me some help?

E:\Python38-32\python.exe D:/pythonProject/pySTC/example.py
D:/pythonProject/pySTC/example.py:21: RuntimeWarning: divide by zero encountered in true_divide
  costs = 1/costs
Traceback (most recent call last):
  File "D:/pythonProject/pySTC/example.py", line 29, in <module>
    stc.embed(input_image, costs, 'files/message.txt', 's3cr3t', 'files/stego.png')
  File "D:\pythonProject\pySTC\stc.py", line 78, in embed
[[1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [0.0178742  0.02157266 0.02523229 ... 0.02048906 0.01882514 0.01686236]
 [0.01601581 0.01954549 0.02305643 ... 0.01872607 0.0171745  0.01529094]
 [0.0141472  0.01750594 0.02085815 ... 0.01721902 0.01574729 0.01393726]]
    lib = cdll.LoadLibrary(os.path.join(me, "lib", "stc.so"))
  File "E:\Python38-32\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "E:\Python38-32\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)

WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by daniellerch** [comment]
For now the library only works in Linux.
